version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: tools.vitruv:*
  commit-message:
    prefix: "Maven"
    include: "scope"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "GitHub Actions"
    include: "scope"