name: Release

# workflow triggers
on:
  # manually
  workflow_dispatch:
  # releases
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Setup Java and Maven cache
      uses: actions/setup-java@v3.13.0
      with:
        distribution: 'temurin'
        java-version: '17'
        check-latest: true
        cache: 'maven'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Deploy to staging and release
      run: >
        ./mvnw clean deploy -P release
        --batch-mode
        --update-snapshots
        --no-transfer-progress
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
